#!/bin/sh

cwd=$(pwd)
git_dir_cwd=$DOTFILE_DIR$cwd
GIT="git --git-dir=/home/michael/devel/config_files/.git \
	--work-tree=/home/michael/devel/config_files/"
#
# BEGIN platform definable
#

uuid_grep(){
	file=$1; shift
	for regexp in "$@"; do
		while [[ -n $(grep -Eo "$regexp" $file | head -n 1) ]]; do
			matched=$(grep -Eo "$regexp" $file | head -n 1)	
			uuid=$(uuidgen)
			sed -i -E "/$regexp/{s/$regexp/$uuid/1; :l n; b l};" $file
			echo $uuid":"$matched"\n"
		done
	done
}
#
# END platform definable
#
#
# BEGIN subcommand functions
#
encrypt_copy(){
	file=$1; shift
	cp_dot $file
	encrypt_grep=$(uuid_grep $git_dir_cwd"/"$file "$@")
	name_file="$(echo $cwd | cut -b 2-)/$file" 
	echo $encrypt_grep | pass insert --echo --force $name_file
}
cp_dot(){
	for file in "$@"; do
		mkdir -p $git_dir_cwd
		cp -r $cwd"/"$file $git_dir_cwd"/"
		$GIT add $git_dir_cwd"/"$file
	done
}
cp_dot_reverse(){
	for file in "$@"; do
#		if [[ -n $PASSWORD_STORE_DIR && -e "$PASSWORD_STORE_DIR$(pwd)/$file" ]]; then
#			encrypt_grep=$( pass show $(pwd)/$file )	
#			echo $encrypt_grep | grep -Eo 
#		fi

		cp -r $git_dir_cwd"/"$file $cwd"/"$file
	done 
}
cp_dot_all(){
	git_files=$(find $DOTFILE_DIR -type f | grep -v ".*git\/" | tr "\n" " ")
	for file in $git_files; do
		orig_file=$(echo $file | cut -b $((${#DOTFILE_DIR}+1))-)
		cp -r $orig_file $file
	done
}
case "$1" in
	-r) shift; cp_dot_reverse "$@" ;;
	-en) shift; encrypt_copy "$@" ;;
	-all) cp_dot_all ;;
	*)   cp_dot "$@" ;;


esac

exit 0
