#!/bin/sh
dir_geth=$HOME"/.local/share/geth"
start_node(){
	port=$1; http_port=$2; node=$3
	geth \
	--ethash.dagdir "$dir_geth/ethash" \
	--datadir "$dir_geth/$node" \
	--networkid 2072 \
	--port $port \
	--nodiscover \
	--http \
	--http.addr 127.0.0.1 \
	--http.port $http_port \
	--allow-insecure-unlock \
	--ipcpath "$dir_geth/$node/geth.ipc" \
	--verbosity 3
}
geth_attach(){
	cd "$dir_geth/node$1"
	geth attach ipc:geth.ipc
}
case "$1" in
	1) start_node 30304 8504 "node1" ;;
	2) start_node 30305 8505 "node2" ;;
	attach) geth_attach "$2"
esac
exit 0
