#!/bin/sh
intern_name="analog-stereo"

profile=$(pacmd list-sinks | grep "device.profile.name.*" | grep -o "$intern_name")
if [[ $profile == $intern_name ]]; then
	pacmd set-card-profile 0 "output:hdmi-stereo+input:analog-stereo"
else
	pacmd set-card-profile 0 "output:analog-stereo+input:analog-stereo"
fi
