#!/bin/sh
intern_sound="analog-stereo"
extern_sound="hdmi-stereo"

profile=$(pacmd list-sinks | grep "device.profile.name.*" | grep -o "$intern_sound")
if [[ $profile == $intern_sound ]]; then
	pacmd set-card-profile 0 output:$extern_sound
else
	pacmd set-card-profile 0 output:$intern_sound
fi
