#!/bin/bash

case "$1" in
	lock) i3lock 
	;;
	logout)
		i3-msg exit
	;;
	turn_monitor_off)
		sleep 1
		xset dpms force off
	;;
	suspend)
		systemctl suspend
	;;
	hibernate)
		systemctl hibernate
	;;
	reboot)
		systemctl reboot
	;;
	shutdown)
		systemctl poweroff 
	;;
	*)
		echo "Usage $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
		exit 2
esac

exit 0
