#!/bin/bash

# rsync -rtvucp --zc=zstd --zl=22 $HOME/./{dl/,docs/,scripts/,devel/c_school/,devel/VirtualBox\ VMs/} michael@10.120.29.73:$HOME/
# rsync -rtvup --ignore-existing /media/michael/HardDrive/Movies/ michael@10.120.29.73:/media/michael/HardDrive/Movies/

# rsync -rtvup --ignore-existing /media/michael/HardDrive/Movies/ michael@10.120.29.73:/media/michael/HardDrive/Movies/

#
# BEGIN platform definable
#
update_list_installed_packages(){
	pacman -Qqe >> $HOME/.config/installed.txt
}
#
# BEGIN rsync functions
#
rsync_remote_media(){
	src=$1; dst=$2
	rsync \
	-rtvup --ignore-existing -e ssh \
	$src $dst
}
rsync_local_media(){
	src=$1; dst=$2
	rsync \
	-rtvup --ignore-existing \
	$src $dst
}
rsync_remote_files(){
	src=$1; dst=$2
	rsync \
	-rtvucpRE --zc=zstd --zl=22 -e ssh \
	--exclude="/home/michael/scripts/bar/volume" \
	--exclude="/home/michael/scripts/bar/battery" \
	$src/./{dl/,docs/,scripts/,pics/,devel/c_school/,devel/VirtualBox\ VMs/} \
	$src/.config/{abook/,aliasrc,fontconfig/,bash/,installed.txt} \
	$src/./.config/BraveSoftware/Brave-Browser/Default/Bookmarks \
	$src/./.config/qutebrowser/{bookmarks,config.py,quickmarks,installed.txt} \
	$src/./.config/abook/ \
	$src/./.config/.ssh/{config,known_hosts} \
	$src/./.config/systemd/user/{*.service,*.timer} \
	$src/./.config/git/ \
	$src/./.config/nvim/init.vim \
	$src/./.config/newsboat/{config,urls} \
	$src/./.config/zsh/{.zprofile,.zshrc} \
	$dst/	
}
rsync_portable(){
	src=$1; dst=$2
	rsync \
	-rtvupRE --delete-after --ignore-existing \
	--exclude="centos8.vdi" --exclude=".git" --exclude="$HOME/pics/wallpapers" \
	$src/{dl/,docs/,scripts/,pics/,devel/c_school/,devel/VirtualBox\ VMs/} \
	$src/.config/{neomutt/,xprofile,Xmodmap,gnupg/,inputrc,mbsync/config,msmtp/config} \
	$src/.local/share/password-store/ \
	$src/.config/{abook/,aliasrc,fontconfig/,bash/,installed.txt} \
	$src/.config/BraveSoftware/Brave-Browser/Default/Bookmarks \
	$src/.config/qutebrowser/{bookmarks,config.py,quickmarks} \
	$src/.config/systemd/user/{*.service,*.timer} \
	$src/.config/git/ \
	$src/.config/nvim/ \
	$src/.config/newsboat/{config,urls} \
	$src/.config/zsh/{.zprofile,.zshrc} \
	/etc/pulse/default.pa \
	$dst
#	$HOME/devel/c_school/ \
	
}
rsync_portable_pull(){
	src=$1; dst=$2
	rsync \
	-rtvupRE --ignore-existing \
	--exclude="centos8.vdi" --exclude=".git" --exclude="$HOME/pics/wallpapers" \
	$src/./{dl/,docs/,scripts/,pics/,devel/c_school/,devel/VirtualBox\ VMs/} \
	$src/./.config/{neomutt/,xprofile,Xmodmap,gnupg/,inputrc,mbsync/config,msmtp/config} \
	$src/./.config/{abook/,aliasrc,fontconfig/,bash/,installed.txt} \
	$src/./.config/BraveSoftware/Brave-Browser/Default/Bookmarks \
	$src/./.config/qutebrowser/{bookmarks,config.py,quickmarks} \
	$src/./.config/systemd/user/{*.service,*.timer} \
	$src/./.config/git/ \
	$src/./.config/nvim/ \
	$src/./.config/newsboat/{config,urls} \
	$src/./.config/zsh/{.zprofile,.zshrc} \
	$dst
#	$HOME/devel/c_school/ \
	
}
#
# END rsync functions
#
#
# BEGIN sync functions
#
sync_local_media(){
	src=$1; dst=$2	
	rsync_local_media $src $dst
	rsync_local_media $dst $src # Syncing it back
}
sync_remote_media(){
	src=$1; dst=$2	
	rsync_remote_media $src $dst
	rsync_remote_media $dst $src # Syncing it back
}
sync_remote_files(){
	rsync_remote_files "$HOME" "$remote_dest:$HOME"
#	rsync_remote_files "$remote_dest:$HOME" "$HOME" #Syncing it back
}
sync_remote_media_files(){
	sync_remote_media "/media/michael/HardDrive/Movies/" \
		"$remote_dest:/media/michael/HardDrive/Movies/"

	sync_remote_media "/media/michael/HardDrive/Music/" \
		"$remote_dest:/media/michael/HardDrive/Music/"
}
#
# END sync functions
#

#
# END platform definable
#

#
# BEGIN subcommand function
# 
cmd_remote(){
	user=$(whoami)
	[[ $(hostname) == "lenovo" ]] && remote_host="desktop" || remote_host="lenovo"
	remote_dest=$user"@"$remote_host
	case "$1" in
		media) shift; sync_remote_media_files ;;
		files) shift; sync_remote_files ;;
	esac
}
cmd_wd(){
	sync_local_media "/media/michael/HardDrive/Movies/" \
			   "/media/michael/ExtDrive/Filmy/"

	sync_local_media "/media/michael/HardDrive/Music/" \
			   "/media/michael/ExtDrive/Music/"
}
cmd_portable(){
	update_list_installed_packages

	dst_flash="/media/michael/FlashDrive/portable-home/"$(hostname)
	dst_hard="/media/michael/HardDrive/portable-home/"$(hostname)
	mkdir -p $dst_flash
	rsync_portable "$HOME" "$dst_hard"
	rsync_portable_pull "$dst_hard$HOME" "$HOME"
	
	rsync_portable "$HOME" "$dst_flash"
	rsync_portable_pull "$dst_flash$HOME" "$HOME"

}
cmd_test(){
	src="/home/michael/"
	dst=$src"data/test-dir/"
	rsync \
	--perms --recursive --times --relative \
	$src./.config/systemd/user/*.service \
	$src./scripts/ \
	$src./.config/{inputrc,Xmodmap,xprofile,aliasrc,mailcap} \
	$src./.config/qutebrowser/{bookmarks,config.py,quickmarks} \
	$src./.config/msmtp/config \
	$src./.config/git/ \
	$src./.config/mpv/ \
	$src./.config/newsboat/{config,urls} \
	$src./.config/mbsync/config \
	$src./.config/nvim/init.vim \
	$src./.config/neomutt/ \
	$src./.config/bash/ \
	$src./.config/zsh/ \
	$src./devel/c_school/ \
	$dst

}
#
# END subcommand functions 
#
case "$1" in
	remote) shift; cmd_remote "$@" ;;
	wd) shift; cmd_wd "$@" ;;
	portable) shift; cmd_portable "$@" ;;
	test) shift; cmd_test "$@" ;;
#	*)   cp_dot "$@" ;;


esac
exit 0
