#!/bin/bash

connet=""
connection(){
	type_con=$1
	str=$2

	id_active=$(nmcli connection show --active | grep "$type_con" | awk -F" " '{print $1}')
	if [[ $id_active != "" ]]; then
		ip4=$(nmcli -g ip4.address connection show $id_active)
		connet=$connet$str$ip4
	fi
}
connection "wifi" "W: "
connection "ethernet" " E: "

echo -n $connet
