#!/bin/sh
volume=$(pacmd list-sinks | grep "volume:.*" | grep -o "[0-9]*%" | head -n 1)
mute=$(pacmd list-sinks | grep "mute.*" | grep -o "yes")
if [[ $mute = "yes" ]]; then
 	echo -n $volume" [off]"
else
	echo -n $volume
fi
